name: GitHub Actions
on: [push]
jobs:
  dev-deploy:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    environment: dev
    steps:
      - run: echo "🎉  ${{ github.event_name }} , ${{ runner.os }}, "
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - run: npm run build --if-present
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE}}
          source: ${{ github.workspace }}/dist
          target: "/usr/share/nginx/html3"
          strip_components: 3
          rm: true
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE}}
          port: ${{ secrets.PORT }}
          script: |
            whoami
  prod-deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    environment: master
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build --if-present
      - run: ls -l ${{ github.workspace }}
      - uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          port: 22
          key: ${{ secrets.KEY }}
          source: ${{ github.workspace }}/dist
          target: "/home/ubuntu/zkid-interface"
          strip_components: 3
          rm: true
